# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: taskflow_analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'taskflow_analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18taskflow_analytics.proto\x12\x12taskflow.analytics\"1\n\x0bTeamRequest\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x11\n\tdays_back\x18\x02 \x01(\x05\"\x9a\x01\n\x0fTeamPerformance\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63ompleted_tasks\x18\x02 \x01(\x05\x12\x15\n\roverdue_tasks\x18\x03 \x01(\x05\x12\x10\n\x08velocity\x18\x04 \x01(\x02\x12\x34\n\x0ctask_metrics\x18\x05 \x03(\x0b\x32\x1e.taskflow.analytics.TaskMetric\"U\n\nTaskUpdate\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0b\x61ssigned_to\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"Z\n\nTaskMetric\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x18\n\x10\x64\x61ys_to_complete\x18\x03 \x01(\x05\x12\x12\n\ncomplexity\x18\x04 \x01(\t\";\n\x11TaskStreamRequest\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x15\n\rstatus_filter\x18\x02 \x03(\t\"I\n\x11TaskUpdateRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"[\n\rBatchResponse\x12\x1a\n\x12successful_updates\x18\x01 \x01(\x05\x12\x16\n\x0e\x66\x61iled_updates\x18\x02 \x01(\x05\x12\x16\n\x0e\x65rror_messages\x18\x03 \x03(\t\"f\n\x11TaskCollaboration\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x32\x90\x03\n\rTaskAnalytics\x12Z\n\x12GetTeamPerformance\x12\x1f.taskflow.analytics.TeamRequest\x1a#.taskflow.analytics.TeamPerformance\x12\\\n\x11StreamTaskUpdates\x12%.taskflow.analytics.TaskStreamRequest\x1a\x1e.taskflow.analytics.TaskUpdate0\x01\x12^\n\x10\x42\x61tchUpdateTasks\x12%.taskflow.analytics.TaskUpdateRequest\x1a!.taskflow.analytics.BatchResponse(\x01\x12\x65\n\x11\x43ollaborateOnTask\x12%.taskflow.analytics.TaskCollaboration\x1a%.taskflow.analytics.TaskCollaboration(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskflow_analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAMREQUEST']._serialized_start=48
  _globals['_TEAMREQUEST']._serialized_end=97
  _globals['_TEAMPERFORMANCE']._serialized_start=100
  _globals['_TEAMPERFORMANCE']._serialized_end=254
  _globals['_TASKUPDATE']._serialized_start=256
  _globals['_TASKUPDATE']._serialized_end=341
  _globals['_TASKMETRIC']._serialized_start=343
  _globals['_TASKMETRIC']._serialized_end=433
  _globals['_TASKSTREAMREQUEST']._serialized_start=435
  _globals['_TASKSTREAMREQUEST']._serialized_end=494
  _globals['_TASKUPDATEREQUEST']._serialized_start=496
  _globals['_TASKUPDATEREQUEST']._serialized_end=569
  _globals['_BATCHRESPONSE']._serialized_start=571
  _globals['_BATCHRESPONSE']._serialized_end=662
  _globals['_TASKCOLLABORATION']._serialized_start=664
  _globals['_TASKCOLLABORATION']._serialized_end=766
  _globals['_TASKANALYTICS']._serialized_start=769
  _globals['_TASKANALYTICS']._serialized_end=1169
# @@protoc_insertion_point(module_scope)
