# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import taskflow_analytics_pb2 as taskflow__analytics__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in taskflow_analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskAnalyticsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTeamPerformance = channel.unary_unary(
                '/taskflow.analytics.TaskAnalytics/GetTeamPerformance',
                request_serializer=taskflow__analytics__pb2.TeamRequest.SerializeToString,
                response_deserializer=taskflow__analytics__pb2.TeamPerformance.FromString,
                _registered_method=True)
        self.StreamTaskUpdates = channel.unary_stream(
                '/taskflow.analytics.TaskAnalytics/StreamTaskUpdates',
                request_serializer=taskflow__analytics__pb2.TaskStreamRequest.SerializeToString,
                response_deserializer=taskflow__analytics__pb2.TaskUpdate.FromString,
                _registered_method=True)
        self.BatchUpdateTasks = channel.stream_unary(
                '/taskflow.analytics.TaskAnalytics/BatchUpdateTasks',
                request_serializer=taskflow__analytics__pb2.TaskUpdateRequest.SerializeToString,
                response_deserializer=taskflow__analytics__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.CollaborateOnTask = channel.stream_stream(
                '/taskflow.analytics.TaskAnalytics/CollaborateOnTask',
                request_serializer=taskflow__analytics__pb2.TaskCollaboration.SerializeToString,
                response_deserializer=taskflow__analytics__pb2.TaskCollaboration.FromString,
                _registered_method=True)


class TaskAnalyticsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTeamPerformance(self, request, context):
        """Unary RPC - get team performance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskUpdates(self, request, context):
        """Server streaming - real-time task updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdateTasks(self, request_iterator, context):
        """Client streaming - batch task updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollaborateOnTask(self, request_iterator, context):
        """Bidirectional streaming - real-time collaboration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskAnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTeamPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeamPerformance,
                    request_deserializer=taskflow__analytics__pb2.TeamRequest.FromString,
                    response_serializer=taskflow__analytics__pb2.TeamPerformance.SerializeToString,
            ),
            'StreamTaskUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskUpdates,
                    request_deserializer=taskflow__analytics__pb2.TaskStreamRequest.FromString,
                    response_serializer=taskflow__analytics__pb2.TaskUpdate.SerializeToString,
            ),
            'BatchUpdateTasks': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchUpdateTasks,
                    request_deserializer=taskflow__analytics__pb2.TaskUpdateRequest.FromString,
                    response_serializer=taskflow__analytics__pb2.BatchResponse.SerializeToString,
            ),
            'CollaborateOnTask': grpc.stream_stream_rpc_method_handler(
                    servicer.CollaborateOnTask,
                    request_deserializer=taskflow__analytics__pb2.TaskCollaboration.FromString,
                    response_serializer=taskflow__analytics__pb2.TaskCollaboration.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskflow.analytics.TaskAnalytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskflow.analytics.TaskAnalytics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskAnalytics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTeamPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskflow.analytics.TaskAnalytics/GetTeamPerformance',
            taskflow__analytics__pb2.TeamRequest.SerializeToString,
            taskflow__analytics__pb2.TeamPerformance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/taskflow.analytics.TaskAnalytics/StreamTaskUpdates',
            taskflow__analytics__pb2.TaskStreamRequest.SerializeToString,
            taskflow__analytics__pb2.TaskUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpdateTasks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/taskflow.analytics.TaskAnalytics/BatchUpdateTasks',
            taskflow__analytics__pb2.TaskUpdateRequest.SerializeToString,
            taskflow__analytics__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollaborateOnTask(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/taskflow.analytics.TaskAnalytics/CollaborateOnTask',
            taskflow__analytics__pb2.TaskCollaboration.SerializeToString,
            taskflow__analytics__pb2.TaskCollaboration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
