services:
  # TaskFlow API
  taskflow-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=taskflow;Username=postgres;Password=password
      - ConnectionStrings__Redis=redis:6379
      - Authentication__Jwt__SecretKey=${JWT_SECRET_KEY}
      - Authentication__Jwt__Issuer=${JWT_ISSUER}
      - Authentication__Jwt__Audience=${JWT_AUDIENCE}
      - Authentication__Jwt__ExpirationMinutes=${JWT_EXPIRATION_MINUTES}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    depends_on:
      - postgres
      - redis
      - seq
    volumes:
      - ./logs:/app/logs
    networks:
      - taskflow-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=taskflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Seq Log Aggregation
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
      - "5342:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
    volumes:
      - seq_data:/data
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin (Optional - Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@taskflow.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - taskflow-network
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:
  seq_data:

networks:
  taskflow-network:
    driver: bridge 